# Generated by Django 4.2.21 on 2026-06-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("product_query", models.CharField(max_length=500)),
                (
                    "canonical_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.IntegerField(default=0)),
                ("status_message", models.CharField(default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("canonical_name", models.CharField(max_length=500)),
                ("category", models.CharField(max_length=200)),
                ("search_terms", models.JSONField(default=list)),
                ("subreddits", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="QueryCache",
            fields=[
                (
                    "raw_query",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("canonical_id", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RawComment",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("text", models.TextField()),
                ("score", models.IntegerField(default=0)),
                ("subreddit", models.CharField(max_length=200)),
                ("post_url", models.URLField(max_length=1000)),
                ("created_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AspectSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspect", models.CharField(max_length=200)),
                ("mention_pct", models.FloatField()),
                ("positive_pct", models.FloatField()),
                ("negative_pct", models.FloatField()),
                (
                    "recent_trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("declining", "Declining"),
                            ("stable", "Stable"),
                        ],
                        max_length=20,
                    ),
                ),
                ("headline", models.TextField()),
                ("detail", models.TextField()),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="summaries",
                        to="core.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AspectClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aspect", models.CharField(max_length=200)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[
                            ("positive", "Positive"),
                            ("negative", "Negative"),
                            ("mixed", "Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quote", models.TextField()),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="core.rawcomment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspect_claims",
                        to="core.product",
                    ),
                ),
            ],
        ),
    ]
