# Generated by Django 4.2.21 on 2026-06-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aspectsummary",
            name="trend_note",
            field=models.TextField(blank=True, default=""),
        ),
    ]
