# Generated by Django 4.2.21 on 2026-06-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_aspectsummary_trend_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="comment_count",
            field=models.IntegerField(default=0),
        ),
    ]
